version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3307:3306" # Ánh xạ cổng 3307 bên ngoài đến cổng 3306 bên trong
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: topVlanceApp
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  mysql_data:
